name: vania_app
description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  vania: ^0.6.2
  intl : ^0.18.0
  bcrypt: ^1.1.3
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.1
  eloquent: ^3.2.1
  mailer: ^6.2.0
  meta: ^1.16.0
  mime: ^1.0.6
  path: ^1.9.1
  sprintf: ^7.0.0
  string_scanner: ^1.4.0
  uuid: ^4.5.1



dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

dependency_overrides:
  pointycastle: 3.7.3